# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'tobiy105/Web-App-DevOps-Project'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Oluwatobi Sobola DevOps(0ebbba45-beb2-4c3a-ae53-2fbb98fc09cc)'
    azureResourceGroup: 'net-dev-aks-rg'
    kubernetesCluster: 'new-my-aks-cluster'
    manifests: 'application-manifest.yaml'
